baseURL = "https://tinkerhub.org/learn/"
title = "TinkerHub Learning Paths"
theme = "tinkerhub"
[Params]
  commentsRepo="tinkerhub/TinkerHub-Learning-Paths-Comments"
[taxonomies]
  type = "types"
enableEmoji = true
pygmentsUseClasses = true
#googleAnalytics = ""
[outputs]
  home =["HTML", "JSON"]
