baseURL = "https://tinkerhub.org/learn/"
title = "TinkerHub Learning Paths"
theme = "tinkerhub"
[taxonomies]
  type = "types"
enableEmoji = true
pygmentsUseClasses = true
#googleAnalytics = ""
[outputs]
  home =["HTML", "JSON"]
