baseURL = "https://tinkerhub.org/learn/"
title = "TinkerHub Learning Paths"
theme = "tinkerhub"
[taxonomies]
  category = "category"
disableKinds = ["tags"]
enableEmoji = true
pygmentsUseClasses = true
#googleAnalytics = ""
[outputs]
  home =["HTML", "JSON"]